/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prerequisites.java
 *
 * Created on Sep 28, 2011, 7:28:14 PM
 */
package conkyscriptbuilder;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author tstreit
 */
public class Prerequisites extends javax.swing.JFrame {
    
    String s;
    String install = "./install.sh";

    /** Creates new form Prerequisites */
    public Prerequisites() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /** Calls process to run install.sh scripts */
    private void Install() {
        try {
            Process p = Runtime.getRuntime().exec(install);
            BufferedReader stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()));
            BufferedReader stdError = new BufferedReader(new InputStreamReader(p.getErrorStream()));
            while ((s = stdInput.readLine()) != null) {
                System.out.println(s);
            } //END OF A WHILE STATEMENT

        } catch (IOException e) {
        } //END OF A CATCH STATEMENT
        this.dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conky Script Builder");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("In the future this will be a set of check boxes to install software.  During beta this feature is not quite ready.\n\nIf you are Debian/Ubuntu distribution please open a terminal and run the following commands:\n\nsudo apt-get update\nsudo apt-get install conky-all wget fortunes python\n\nIf conky doesn't automatically start for you run the following command:\n\nconky &\n\nThen close the terminal and conky should still be running for you.\n\nIf you are Red Hat 5/Fedora 14 or lower distribution please open a terminal and run the following commands:\n\nsudo yum update\nsudo yum install conky-all wget fortunes python\n\nIf conky doesn't automatically start for you run the following command:\n\nconky &\n\nThen close the terminal and conky should still be running for you.\n\nIf you are Red Hat 6/Fedora 15 or higher distribution please open a terminal and run the following commands:\n\nsudo yum update\nsudo yum install conky-all wget lshw fortunes python\n\nIf conky doesn't automatically start for you run the following command:\n\nconky &\n\nThen close the terminal and conky should still be running for you.\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("You will need to install some customized scripts, you can do this automatically by clicking this button:");

        jButton1.setText("Install");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Install();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
